version: "3"
services:
  nginx:
    image: "nginx:latest"
    container_name: "chat_internal_nginx"
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - chat_network
    links:
      - php

  php:
    container_name: "chat_internal_php"
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      WWWUSER: "${WWWUSER}"
    volumes:
      - ".:/var/www/html"
    networks:
      - chat_network

networks:
  chat_network:
    driver: bridge
